FSD is Based on OOPS Concepts
AMubinshaikh/FSD pull request #7
Opened 2020-10-05 09:49 UTC by AMubinshaikh

In this FSD-1 containing oops concepts examples
1.Abstraction
2.Polymorphism
3.Encapsulation
4.Inheritance
5.MultilevelInheritance
6.Interface
7.Method Overriding
all files have one entry point Main() method in Program.cs

2020-10-06 14:11 UTC, abdulmuheet requested changes
@AMubinshaikh Please see my comments inline.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/ Bank.cs
> +        private int _pin;
do not use underscore( _ ) in a variable names.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/ Bank.cs
> +        public string AccountHolderName { get { return _AccountHolderName; }
Correct the indentation, get{} should be in next line.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/ Bank.cs
> +        private void Displaypin()
Rename Displaypin -> DisplayPin

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/ Bank.cs
> +          public void display()
The method names should follow pascal casing.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/AddingNumbers.cs
> +         public static int AddNumbers(int number1, int number2)
Why it's "static" where other one with 3 params are not?

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/AddingNumbers.cs
> +               return number1 +number2;
Add space after + as well.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/CarShowroom.cs
> +    private int _CarKeyCode;
Indentation seems incorrect.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/CarShowroom.cs
> +    private string _EngineCode;
use the proper naming convention for variables.

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/ICoachingCentre.cs
> +//means function declared but withod body
typo "withod" please check typing error in all the files(If any)

2020-10-06 14:11 UTC, abdulmuheet commented on Oops_Concepts/Program.cs
> +             Console.WriteLine("The sum of two Number is = "
It should be sum of "three" numbers...

2020-10-06 14:51 UTC, AMubinshaikh commented on Oops_Concepts/ Bank.cs
> +        private int _pin;
ok

2020-10-06 14:52 UTC, AMubinshaikh commented on Oops_Concepts/ Bank.cs
> +        public string AccountHolderName { get { return _AccountHolderName; }
ok

2020-10-06 14:52 UTC, AMubinshaikh commented on Oops_Concepts/ Bank.cs
> +        private void Displaypin()
ok

2020-10-06 14:53 UTC, AMubinshaikh commented on Oops_Concepts/ Bank.cs
> +          public void display()
ok

2020-10-08 18:56 UTC, abdulmuheet approved these changes
Looks good

2020-10-17 07:40 UTC, merged